# License policy used when cargo-about builds the dependency report.
accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "GPL-3.0-or-later",
    "ISC",
    "MPL-2.0",
    "NCSA",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "0BSD",
]

targets = ["x86_64-unknown-linux-gnu"]
ignore-dev-dependencies = true
workarounds = ["ring", "rustix", "rustls"]
private = { ignore = true }
